package com.labyrinthconquest.game.data;

/**
 * Important variables that do not change are stored here
 */
public class Constants {
    private Constants() {}

    public static final String LOG_TAG = "Labyrinth-Conquest";

    public static final String PLAYER_WATER_ANIMATION_SHEET = "textures/player_water_walk_cycle.png";
    public static final String PLAYER_CLIMB_ANIMATION_SHEET = "textures/player_strong_walk_cycle.png";
    public static final String PLAYER_STRONG_ANIMATION_SHEET = "textures/player_climb_walk_cycle.png";
    public static final int PLAYER_ANIMATION_SHEET_COLUMNS = 7;
    public static final int PLAYER_ANIMATION_SHEET_ROWS = 1;
    public static final float PLAYER_WIDTH = 0.5f;
    public static final float PLAYER_HEIGHT = 0.8f;
    public static final float PLAYER_COLLISION_RADIUS = 0.46f;
    public static final int LEVELS_COUNT = 6;
    /**
     * Time that player has to travel for without node path node change until path is stopped. Prevents e.g traveling towards a wall forever
     */
    public static final float PLAYER_TIME_SINCE_LAST_MOVE_CUT = 4f;
    /**
     *  Draw the player texture slightly above the center so it the collisions appear closer to the feet
     */
    public static final float PLAYER_ANIMATION_VERTICAL_DRAW_OFFSET = 0.14f;

    public static final float WINDOW_WIDTH = 25f;
    public static final float WINDOW_HEIGHT = 16f;
    public static final float MENU_VIEWPORT_WIDTH = 854;
    public static final float MENU_VIEWPORT_HEIGHT = 480;
    public static final int TILE_WIDTH = 32;
    public static final int TILE_HEIGHT = 32;
    public static final float COLLISION_TIME_STEP = 0.0166f;
    public static final float ANIMATION_FRAME_LENGTH = 0.15f;
    public static final float TILE_MAP_UNIT_SCALE = 0.03125f;
    public static final float MAX_ANIMATION_FRAME_TIME = 0.25f;
    /**
     * Offset when checking if touch position is near a player
     */
    public static final float PLAYER_ACTIVATION_OFFSET = 0.5f;
    public static final float PLAYER_SPEED_MULTIPLIER = 3.2f;
    /**
     * Minimum distance to the touch pos needed to add it as a node to the path that was generated by findPath
     */
    public static final float TIME_SINCE_LAST_PATH_CUTOFF = 0.44f;
    public static final float PATH_SMOOTH_SIDE_OFFSET = 0.61f;

    /**
     * Tilemap tags
     */
    public static final String MAP_WALLS_STATIC = "walls_static";
    public static final String MAP_WALLS_STRONG = "walls_strong";
    public static final String MAP_WALLS_CLIMB = "walls_climb";
    public static final String MAP_WALLS_WATER = "walls_water";
    public static final String MAP_WALLS_TEXTURES = "walls_doors_buttons_textures";
    public static final String MAP_GOAL = "goal";
    public static final String MAP_SPAWNS = "spawns";

    /**
     * Spawn tags
     */
    public static final String MAP_SPAWNPOINT_STRONG = "strongPoint";
    public static final String MAP_SPAWNPOINT_CLIMBER = "climberPoint";
    public static final String MAP_SPAWNPOINT_WATER = "waterPoint";

    /**
     * Layer that contains tiles that can have pathfind nodes
     */
    public static final String MAP_PATHFINDER_NODES_WATER = "pathfind_nodes_water";
    public static final String MAP_PATHFINDER_NODES_CLIMB = "pathfind_nodes_climb";
    public static final String MAP_PATHFINDER_NODES_STRONG = "pathfind_nodes_strong";

    /**
     * Player id tags
     */
    public static final String PLAYER_STRONG = "Strong";
    public static final String PLAYER_CLIMB = "Climb";
    public static final String PLAYER_WATER = "Water";

    /**
     * Door/button tags
     */
    public static final String MAP_DOORS = "doors";
    public static final String MAP_BUTTONS = "buttons";
    public static final String MAP_BUTTON = "button";

    /**
     * Collision categories (defines what they are)
     */
    public static final short CAT_MAP_WALLS_STATIC = 1;
    public static final short CAT_MAP_WALLS_STRONG = 2;
    public static final short CAT_MAP_WALLS_CLIMB = 4;
    public static final short CAT_MAP_WALLS_WATER = 8;
    public static final short CAT_MAP_WALLS_BUTTONS = 16;
    public static final short CAT_MAP_WALLS_DOORS = 32;
    public static final short CAT_MAP_GOAL = 64;

    public static final short CAT_PLAYER_STRONG = 128;
    public static final short CAT_PLAYER_CLIMB = 256;
    public static final short CAT_PLAYER_WATER = 512;

    /**
     * Collision masks (defines what they collide with)
     */
    public static final short MASK_PLAYER_STRONG = CAT_MAP_WALLS_STATIC | CAT_MAP_WALLS_STRONG | CAT_MAP_WALLS_CLIMB | CAT_MAP_WALLS_WATER
            | CAT_MAP_WALLS_BUTTONS | CAT_MAP_WALLS_DOORS | CAT_MAP_GOAL;
    public static final short MASK_PLAYER_CLIMB = CAT_MAP_WALLS_STATIC | CAT_MAP_WALLS_STRONG | CAT_MAP_WALLS_WATER | CAT_MAP_WALLS_BUTTONS | CAT_MAP_WALLS_DOORS | CAT_MAP_GOAL;
    public static final short MASK_PLAYER_WATER = CAT_MAP_WALLS_STATIC | CAT_MAP_WALLS_STRONG | CAT_MAP_WALLS_CLIMB | CAT_MAP_WALLS_BUTTONS | CAT_MAP_WALLS_DOORS | CAT_MAP_GOAL;

    /**
     * Settings preference and localisation locations
     */
    public static final String PREFERENCES_FILE_NAME = "Preferences";
    public static final String VOLUME_PREFS_LOCATION = "volume";
    public static final String USERNAME_PREFS_LOCATION = "username";
    public static final String USERNAME_PREFS_DEFAULT = "Username";
    public static final String LOCALISATION_PREFS_LOCATION = "Localisation";
}
